[package]
name = "leo"
version = "0.1.0"
authors = ["The Aleo Team <hello@aleo.org>"]
edition = "2018"

[lib]
name = "leo"
path = "src/lib.rs"

[[bin]]
name = "leo"
path = "src/main.rs"

[dependencies]
from-pest = "0.3.1"
lazy_static = "1.3.0"
pest = "2.0"
pest_derive = "2.0"
pest-ast = "0.3.3"
rand = { version = "0.7" }

snarkos-algorithms = { path = "../snarkOS/algorithms" }
snarkos-curves = { path = "../snarkOS/curves" }
snarkos-errors = { path = "../snarkOS/errors" }
snarkos-gadgets = { path = "../snarkOS/gadgets" }
snarkos-models = { path = "../snarkOS/models" }
