[package]
name = "leo-types"
version = "0.1.0"
authors = ["The Aleo Team <hello@aleo.org>"]
edition = "2018"

[dependencies]
leo-ast = { path = "../ast", version = "0.1.0" }
leo-inputs = { path = "../leo-inputs", version = "0.1.0" }

snarkos-errors = { path = "../../snarkOS/errors", version = "0.8.0", default-features = false }
snarkos-models =  { path = "../../snarkOS/models", version = "0.8.0", default-features = false }

pest = { version = "2.0" }
serde = { version = "1.0" }
thiserror = { version = "1.0" }
