[package]
name = "leo-ast"
version = "0.1.0"
authors = ["howardwu <howardwu@berkeley.edu>"]
edition = "2018"

[dependencies]
from-pest = { version = "0.3.1" }
lazy_static = { version = "1.3.0" }
pest = { version = "2.0" }
pest-ast = { version = "0.3.3" }
pest_derive = { version = "2.0" }
