[package]
name = "leo-ast"
version = "1.0.1"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "AST of the Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = ["aleo", "cryptography", "leo", "programming-language", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "web-programming"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[[bin]]
name = "leo_ast"
path = "src/main.rs"

[[bench]]
name = "ast"
path = "benches/ast.rs"
harness = false

[dependencies]
from-pest = { version = "0.3.1" }
lazy_static = { version = "1.3.0" }
pest = { version = "2.0" }
pest-ast = { version = "0.3.3" }
pest_derive = { version = "2.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
thiserror = { version = "1.0" }
tracing = { version = "0.1" }


[dev-dependencies]
criterion = { version = "0.3" }

[features]
default = []
ci_skip = []
