[package]
name = "leo-compiler"
version = "0.1.0"
authors = ["The Aleo Team <hello@aleo.org>"]
edition = "2018"

[dependencies]
leo-ast = { path = "../ast", version = "0.1.0" }
leo-types = { path = "../types", version = "0.1.0" }

snarkos-curves = { path = "../../snarkOS/curves", version = "0.8.0" }
snarkos-errors = { path = "../../snarkOS/errors", version = "0.8.0" }
snarkos-gadgets = { path = "../../snarkOS/gadgets", version = "0.8.0" }
snarkos-models =  { path = "../../snarkOS/models", version = "0.8.0" }

hex = { version = "0.4.2" }
log = { version = "0.4" }
rand = { version = "0.7" }
sha2 = { version = "0.8" }
thiserror = { version = "1.0" }

[dev-dependencies]
snarkos-utilities = { path = "../../snarkOS/utilities", version = "0.8.0" }
