name: Leo-ACL2
on: 
  push:
env: 
  RUST_BACKTRACE: 1

jobs:
  acl2:
    name: leo-acl2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Generate asts
        run: |
          cargo run -p leo-test-framework --bin tgc

      # Pull the latest release from the leo-acl2-bin repo, and put it into the
      # repo/acl2 directory. After it's done, unpack the tgz file locally.
      - name: Pull the tgc executable
        run: |
          mkdir acl2 && cd acl2;
          wget $(curl -s https://api.github.com/repos/AleoHQ/leo-acl2-bin/releases/latest \
              | grep "browser_download_url.*.tgz"  \
              | cut -d : -f 2,3 \
              | tr -d \" \
              | xargs)

          tar -xvzf $(ls)
      
      # Using the prepared ASTs and the pulled and unzipped tgc run theorem generation.
      - name: Run tgc over the asts
        run: |
          ARRAY=();
          for dir in `ls tmp/tgc`;
          do
            cd tmp/tgc/$dir; # enter the directory
            ./../../../acl2/tgc canonicalization initial_ast.json canonicalization_ast.json canonicalization-theorem.lisp || ARRAY+=("$dir");
            cd ../../..
          done;
          echo "Failures:";
          for i in ${ARRAY[@]};
          do
          echo $i;
          done;
