name: Add-Contributor

on:
  issues:
    types: [opened]

jobs:
  validate_and_add_contributor:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
      
    - name: Install dependencies
      run: |
        npm install @actions/github@6.0.0 @octokit/rest@20.0.2
        
    - name: Run the script to process the issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node .github/scripts/add_contributor.js
